name: Python Application

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 2 * * 1,5'

jobs:
  using-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: downloading data
        run: python gettingNow.py

      - name: git commit
        run: |
          git config --global user.email zly@lyzhang.me
          git config --global user.name sz[bot]
          git add -A
          git commit -a -m "update data"
      
      - name: push changes
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}